### ISSUE TITLE
ts-node: Permission denied

### ISSUE THREAD

**Issue by saladxuanzhi** [juzeon/dmzj-auto#1]
Linux端运行时报出ts-node: Permission denied
添加--unsafe-perm后依然报错

**Comment by juzeon** [comment]
请尝试全局安装ts-node及typescript：

```shell
npm i -g ts-node typescript
```

然后手动运行：

```shell
ts-node src/daily.ts
ts-node src/weekly.ts
```

**Comment by saladxuanzhi** [comment]
> 请尝试全局安装ts-node及typescript：
> 
> ```shell
> npm i -g ts-node typescript
> ```
> 
> 然后手动运行：
> 
> ```shell
> ts-node src/daily.ts
> ts-node src/weekly.ts
> ```

谢谢作者大大，已成功解决问题
